name: Convert Markdown to PDF

on:
  push:
    branches:
      - '*'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pandoc
      run: |
        sudo apt-get -y update
        sudo apt-get install pandoc texlive-latex-base

    - name: Convert Markdown to PDF
      run: pandoc --from=gfm --to=pdf -o resume_karthik_ganesan.pdf resume.md