name: Convert Markdown to PDF

on:
  push:
    branches:
      - '*'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pandoc
      run: sudo apt-get install pandoc

    - name: Convert Markdown to PDF
      run: pandoc -s resume.md -o resume_karthik_ganesan.pdf
